### ISSUE TITLE
Make camera work

### ISSUE THREAD

**Issue by daphtdazz** [daphtdazz/BleBrowser#14]
So that you can use a webcam using normal javascript APIs from within WebBLE.

**Comment by gfwilliams** [comment]
This would be really cool.

I've been looking at Smartibot (and the general idea of using a phone to control a robot).

There's loads of neat computer vision stuff online like: https://hackernoon.com/handtrackjs-677c29c1d585

You could then use Web Bluetooth to control the robot itself. This'd work on Android, and Safari seems to support getUserMedia. Unfortunately WebBLE doesn't.

It may just be a case of handling the permissions request when the web browser asks 'do you want to let this page access the webcam'?
