### ISSUE TITLE
Writing and notifying from the same characteristic

### ISSUE THREAD

**Issue by Thosty** [daphtdazz/BleBrowser#18]
It seems to me that it is not possible to write and notify from the same chatacteristic. Can someone please check that?

**Comment by daphtdazz** [comment]
Hi Thosty, have you got some example code?

**Comment by Thosty** [comment]
The problem was that there were multiple characteristics with the same ID as I described [here](https://github.com/daphtdazz/BleBrowser/issues/7). I tried to notify from the chatacteristic that has only the property "write". Of course that is not possible.
